directories:
  output: desktop-release-new
  buildResources: build
appId: com.autosupply.desktop
productName: Autosupply
asar: false
files:
  - filter:
      - dist/**/*
      - server.js
      - electron.cjs
      - package.json
      - .env*
      - node_modules/**/*
win:
  target: nsis
electronVersion: 38.8.6
